import requests
import random

WEBHOOK_URL = "https://discord.com/api/webhooks/1486345574381781174/rI48O2F5oqGb6wjl4sJ8LjapIOBwTEURK9XaXPsllUmVcO9wlQmhQkpCyWq109msUkFN"

MESSAGES = [
    "Hello guys. I told my therapist about my suicidal thoughts. She made me pay in advance.",
    "Sup everyone. I bought some shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
    "Hey chat. My grief counselor died yesterday. He was so good, I didn't even care.",
    "Yo. What's the difference between a joke and a rhetorical question?",
    "Greetings mortals. I asked my dog to fetch me a newspaper. He told me to use my phone. I forgot I don't have a dog.",
    "Hello guys. Even people who are good for nothing have the capacity to bring a smile to your face. For instance, when you push them down the stairs.",
    "What's up. I threw a boomerang a few years ago. I now live in constant fear.",
    "Hello everyone. A blind man walks into a bar. And a table. And a chair.",
    "Hey. My grandfather has the heart of a lion and a lifetime ban from the local zoo.",
    "Welcome. I don't have a carbon footprint. I just drive everywhere.",
    "Hello guys. My boss told me to have a good day, so I went home.",
    "Sup. I was playing chess with my friend and he said, 'Let's make this interesting.' So we stopped playing chess.",
    "Yo. I’m starting a charity for people with premature ejaculation. It’s coming quickly.",
    "Greetings. What do you call a cheap circumcision? A rip-off.",
    "Hello guys. I’m reading a book on the history of glue. I can’t put it down. Please send help.",
    "Hey chat. My wife and I have reached the difficult decision that we do not want children. If anybody does, please just send me your contact details.",
    "Sup. I visited my friend at his new house. He told me to make myself at home. So I threw him out.",
    "Hello guys. I told my doctor that I broke my arm in two places. He told me to stop going to those places.",
    "Yo. Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "Hey everyone. I accidentally drank a bottle of invisible ink last night. I'm currently in the hospital waiting to be seen.",
    "Greetings. I'd make a joke about my aim, but I'd probably miss the punchline.",
    "Hello guys. My girlfriend’s dog died, so I tried to cheer her up by getting her an identical one. It just made her more upset. She screamed at me, 'What am I supposed to do with two dead dogs?'",
    "Sup. Women only call me ugly until they find out how much money I make. Then they call me ugly and poor.",
    "Hey chat. I have a stepladder because my real ladder left when I was just a kid.",
    "Yo. My daughter asked me how the stars die. I said, 'Usually from a drug overdose.'",
    "Hello guys. I don't have a beer belly. I have a protective covering for my rock-hard abs.",
    "Greetings. I used to play sports. Then I realized you can buy trophies. Now I'm good at everything.",
    "What's up. 'I'm sorry' and 'I apologize' mean the same thing. Except at a funeral.",
    "Hello guys. What’s the difference between me and cancer? My dad didn't beat cancer.",
    "Hey. My wife told me to stop impersonating a flamingo. I had to put my foot down.",
    "Sup everyone. Why don't skeletons fight each other? They don't have the guts.",
    "Hello guys. I recently decided to sell my vacuum cleaner as all it was doing was gathering dust.",
    "Yo. I just read that someone in the world is stabbed every 52 seconds. Poor guy.",
    "Greetings. As I get older, I remember all the people I lost along the way. Maybe a career as a tour guide wasn't the right choice.",
    "Hello guys. The doctor gave me one year to live, so I shot him. The judge gave me 15 years. Problem solved.",
    "Hey chat. I know a lot of jokes about unemployed people but none of them work.",
    "Sup. I tried to start a hot air balloon business, but it never really took off.",
    "Yo. What's red and bad for your teeth? A brick.",
    "Hello guys. My wife left me because of my insecurity. Oh wait, she's back. She just went to get milk.",
    "Greetings. They laughed when I said I wanted to be a comedian. Well, they're not laughing now.",
    "Hey. I’ve been addicted to cold turkey for two years. I really need to quit cold turkey.",
    "Hello guys. Cremation is my last hope for a smoking hot body.",
    "Sup. It’s sad that a family can be torn apart by something as simple as a pack of wild dogs.",
    "Yo. You don't need a parachute to go skydiving. You need a parachute to go skydiving twice.",
    "Greetings. My son, who's been playing a lot of video games, asked me what happens when you die. I told him you have to wait for someone to find your body and loot it.",
    "Hello guys. To the wheelchair bound guy who stole my camouflage jacket: You can hide, but you can't run.",
    "Hey chat. I asked God for a bike, but I know God doesn't work that way. So I stole a bike and asked for forgiveness.",
    "Sup. What's the hardest part of a vegetable to eat? The wheelchair.",
    "Yo. My teammates are like a broken compass. They have no idea where they're going.",
    "Hello guys. What’s the difference between jelly and jam? You can’t jelly a clown car into a parking space.",
    "Greetings. My grandfather says I'm too reliant on technology. I called him a hypocrite and unplugged his life support.",
    "Hey. I’m on a whiskey diet. I’ve lost three days already.",
    "Hello guys. I got an email saying, 'At hacker school, we hack you!' I don't know why I clicked the link, but now my mouse is moving on its own.",
    "Sup everyone. Working in a mirror factory is something I could totally see myself doing.",
    "Yo. I asked my North Korean friend how it was there, he said he couldn't complain.",
    "Greetings. It turns out that when asked who your favorite child is, you're expected to name one of your own.",
    "Hello guys. I childproofed my house... but they still get in.",
    "Hey chat. What's the difference between a police officer and a bullet? When a bullet kills someone else, you know it's been fired.",
    "Sup. I have many jokes about wealthy people, but they just don't make cents.",
    "Yo. The cemetery is incredibly popular. People are just dying to get in there.",
    "Hello guys. I hate double standards. Burn a body at a crematorium, you're 'doing a great job.' Do it at home and you're 'destroying evidence.'",
    "Greetings. Why did the old man fall in the well? Because he couldn't see that well.",
    "Hey. I’d tell you a joke about an unsharpened pencil, but there’s no point.",
    "Hello guys. Why do vampires seem sick? They're always coffin.",
    "Sup. What’s the worst thing about playing Russian Roulette with someone who has Alzheimer’s? They keep forgetting if they loaded it.",
    "Yo. The first rule of Alzheimer's club is... wait, what are we talking about?",
    "Greetings. I got fired from the keyboard factory today. I wasn't putting in enough shifts.",
    "Hello guys. Never break someone's heart, they only have one. Break their bones, they have 206.",
    "Hey chat. My friend's bakery burned down last night. Now his business is toast.",
    "Sup. I tried to sue the airport for misplacing my luggage. I lost my case.",
    "Yo. I poured root beer into a square glass. Now I just have beer.",
    "Hello guys. People who use selfie sticks really need to take a good long look at themselves.",
    "Greetings. What’s the difference between a hippo and a zippo? One is really heavy, and the other is a little lighter.",
    "Hey. Dark humor is like food. Not everyone gets it.",
    "Hello guys. They say there's safety in numbers. Tell that to six million Jews.",
    "Sup. If at first you don't succeed... then skydiving definitely isn't for you.",
    "Yo. Someone stole my mood ring. I don't know how I feel about that.",
    "Greetings. A computer once beat me at chess, but it was no match for me at kickboxing.",
    "Hello guys. What's the best part about being a necrophiliac? You never have to bring flowers.",
    "Hey chat. I told my friends I was going to make a bike out of spaghetti. They didn't believe me until I rode pasta.",
    "Sup. What do you call a dog with no legs? Doesn't matter, he's not coming anyway.",
    "Yo. When I die, I want to go peacefully in my sleep like my grandfather. Not screaming in terror like the passengers in his car.",
    "Hello guys. I bought a wooden car, wooden engine, wooden doors, wooden wheels. Guess what? It wooden go.",
    "Greetings. I gave a blind man some cheese graters for his birthday. He said it was the most violent book he's ever read.",
    "Hey. Why did the man miss the funeral? He wasn’t a mourning person.",
    "Hello guys. I broke my finger today. On the other hand, I'm completely fine.",
    "Sup. My ex-wife still misses me. But her aim is steadily improving.",
    "Yo. I have a fear of elevators, so I've been taking steps to avoid them.",
    "Greetings. If you see a robbery at an Apple Store, does that make you an iWitness?",
    "Hello guys. Why do orphans make bad baseball players? They don't know where home is.",
    "Hey chat. I swallowed a dictionary. It gave me thesaurus throat I've ever had.",
    "Sup. I was wondering why the frisbee was getting bigger, and then it hit me.",
    "Yo. I hate Russian dolls. They're so full of themselves.",
    "Greetings. My buddy asked if he could crash on my couch. I told him no, my couch doesn't have airbags.",
    "Hello guys. I invented a new word! Plagiarism!",
    "Hey. What's the difference between an oral thermometer and a rectal thermometer? The taste.",
    "Sup everyone. You know you're ugly when it comes to a group picture and they hand you the camera.",
    "Hello guys. My girlfriend dumped me, so I stole her wheelchair. Guess who came crawling back.",
    "Yo. I wanted to be a doctor, but I didn't have the patients.",
    "Greetings. A termite walks into a bar and asks, 'Is the bar tender?'",
    "Hello guys. Why don't cannibals eat clowns? They taste funny.",
    "Hey chat. Did you hear about the guy who had his left side cut off? He's all right now.",
    "Sup. I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Yo. What's the difference between a snowman and a snowwoman? Snowballs.",
    "Greetings. I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
    "Hello guys. My boss says I have a preoccupation with vengeance. We'll see about that.",
    "Hey. Why do scuba divers fall backwards out of the boat? Because if they fell forwards, they'd still be in the boat.",
    "Sup. I just found out I'm colorblind. The diagnosis came completely out of the purple.",
    "Hello guys. Let's talk about my favorite game mechanism: getting headshotted the second I peek.",
    "Yo. What's the hardest thing about making a dead baby joke? The delivery.",
    "Greetings. Why don't blind people skydive? Because it scares the hell out of their dogs.",
    "Hello guys. I got an automated call saying I had won a cruise. I pressed 1, and now my identity is floating in the Caribbean.",
    "Hey chat. I used to be arrogant, but now I'm perfect.",
    "Sup. I told my doctor I have a problem with my hearing. He said, 'Can you describe the symptoms?' I said, 'Homer is fat and Marge has blue hair.'",
    "Yo. Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Greetings. I don't trust stairs. They're always up to something.",
    "Hello guys. What’s the difference between a baby and a sweet potato? About 140 calories.",
    "Hey. I’d love to tell you a joke about a missing person, but I can’t find the punchline.",
    "Sup. I bought a ceiling fan today. I’m going to use it to blow my brains out.",
    "Yo. I’m thinking about removing my spine. I feel like it’s holding me back.",
    "Hello guys. What do you call a fish wearing a bowtie? Sofishticated.",
    "Greetings. The surgeon said the operation was a success, but the patient died. At least the tumor is safe.",
    "Hey chat. I don't have a gambling problem. I'm winning. The casino has a paying problem.",
    "Sup. I tried to write a theater script about a pun, but it was just a play on words.",
    "Hello guys. My roommate said he’d be back in 5 minutes. That was 5 years ago. I’m starting to think he lied.",
    "Yo. My computer crashed so hard it took my will to live with it.",
    "Greetings. What do you call an IT teacher who touches up his students? A PDF file.",
    "Hello guys. Someone asked me to name two structures that hold water. I said 'Well, damn.'",
    "Hey. I ordered a chicken and an egg from Amazon. I'll let you know which comes first.",
    "Sup. What's the difference between a pregnant woman and a lightbulb? You can unscrew a lightbulb.",
    "Hello guys. My granddad always used to say, 'As one door closes, another one opens.' Lovely man. Terrible cabinet maker.",
    "Yo. Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
    "Greetings. How do you make a tissue dance? You put a little boogie in it.",
    "Hello guys. My wife told me to go get those little pills that help get me going. So I bought her some diet pills.",
    "Hey chat. The sole purpose of a child's middle name, is so he can tell when he's really in trouble.",
    "Sup. I went to a seminar on how to avoid falling for scams. It was great, and it only cost me $5,000.",
    "Yo. How many cops does it take to change a lightbulb? None, they just beat the room for being black.",
    "Hello guys. I don't suffer from insanity. I enjoy every minute of it.",
    "Greetings. I bought a dictionary today. The first thing I did was look up the word 'idiot'. Turns out, it was just a picture of the guy who sold me the dictionary.",
    "Hey. What do you call a nun in a wheelchair? Virgin mobile.",
    "Hello guys. I was going to tell a time-traveling joke, but you guys didn't like it.",
    "Sup. Why did the bullet end up losing his job? He got fired.",
    "Yo. People always say 'You are what you eat.' But I don't remember eating a massive disappointment.",
    "Greetings. I’d tell a joke about my internet connection, but it keeps buff...",
    "Hello guys. I was playing Russian Roulette with my friend. I guess I won, because he isn't talking to me anymore.",
    "Hey chat. What do you get when you mix human DNA with goat DNA? Kicked out of the petting zoo.",
    "Sup. I'm reading a horror story in Braille. Something bad is about to happen, I can feel it.",
    "Hello guys. My parents raised me as an only child, which really pissed off my brother.",
    "Yo. Why do orphans work so many shifts? Because they don't have to go home.",
    "Greetings. What do you call it when a ginger goes crazy? A ginger snap.",
    "Hello guys. I put my phone in airplane mode, but it still wouldn't fly. False advertising.",
    "Hey. My doctor told me to watch my drinking. Now I drink in front of a mirror."
]

def run_booster():
    base_message = random.choice(MESSAGES)
    # Formatted with spaces inside the spoiler tags: || @tag1 @tag2 ||
    hidden_tags = " 😂"
    
    payload = {"content": base_message + hidden_tags}
    
    try:
        response = requests.post(WEBHOOK_URL, json=payload)
        response.raise_for_status()
        print("Message sent successfully!")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    run_booster()
